version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}

  deploy-to-heroku:
    executor: heroku/default
    parameters:
      app-name:
        default: $HEROKU_APP_NAME
        type: string
    steps:
      - checkout
      - heroku/install
      - run:
            command: |
              if [ "${CIRCLE_BRANCH}" == "develop" ]
              then
                app-name: ${$HEROKU_APP_NAME_MASTER}
              fi
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@1.2.3

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-heroku:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
