version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}

  deploy-to-heroku:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Push in Heroku git
          working_directory: /
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_MASTER.git master --delete
            elif [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master --delete
            fi

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-heroku:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
